namespace :make_region_plants do
  desc "make regions of hong kong"
  task :create => :environment do

    grasslands = [
      "Cynodon dactylon",
      "Cyrtococcum patens",
      "Digitaria sanquinalis",
      "Echinochloa crus-galli",
      "Eleusine indica",
      "Imperata cylindrica",
      "Ischaemum aristatum",
      "Miscanthus sinensis",
      "Neyraudia arundinaceae",
      "Panicum maximum",
      "Paspalum conjugatum",
      "Paspalum scrobiculatum",
      "Pennisetum alopecuroides",
      "Rhynchelytrum repens",
      "Thysanolaena maxima",
      "Abutilon indicum",
      "Achyranthes aspera",
      "Ageratum conyzoides",
      "Amaranthus spinosus",
      "Amaranthus viridis",
      "Bidens bipinnata",
      "Cassia tora",
      "Chrysanthemum frutescens",
      "Chrysanthemum indicum",
      "Conyza bonariensis",
      "Crotalaria pallida",
      "Desmodium heterocarpon",
      "Eclipta prostrata",
      "Elephantopus scaber",
      "Elephantopus spicatus",
      "Elephantopus tomentosa",
      "Emilia sonchifolia",
      "Gahnia tristis",
      "Hedyotis acutangula",
      "Inula cappa",
      "Polygonum chinense",
      "Mimosa pudica",
      "Alysicarpus vaginalis",
      "Millettia nitida",
      "Paederia scandens",
      "Phyllodium pulchellum",
      "Pueraria lobata",
      "Rubus reflexus",
      "Scleria levis",
      "Sida rhombifolia",
      "Spilanthes acmella",
      "Synedrella nodiflora",
      "Vernonia cinerea"
    ]

    shrublands = [
      "Aporusa dioica",
      "Baeckea frutescens",
      "Boehmeria nivea",
      "Breynia fruticosa",
      "Bridelia tomentosa",
      "Crotalaria pallida",
      "Eurya chinensis",
      "Evodia lepta",
      "Ficus hispida",
      "Ficus variegata",
      "Glochidion eriocarpum",
      "Gordonia axillaris",
      "Ilex asprella",
      "Litsea rotundifolia",
      "Melastoma candidum",
      "Melastoma dodecandrum",
      "Melastoma sanguineum",
      "Millettia dielsiana",
      "Mimosa pudica",
      "Phyllanthus emblica",
      "Psychotria rubra",
      "Pteroloma triquetrum",
      "Rhaphiolepis indica",
      "Rhodomyrtus tomentosa",
      "Rubus reflexus",
      "Sapium discolor",
      "Schefflera octophylla",
      "Sterculia lanceolata",
      "Tetracera asiatica"
    ]

    woodlands = [
      "Alangium chinense",
      "Aquilaria sinensis",
      "Cinnamomum camphora",
      "Diospyros morrisiana",
      "Ficus",
      "Liquidambar formosana",
      "Lithocarpus",
      "Litsea",
      "Machilus",
      "Sapium discolor",
      "Schefflera octophylla",
      "Sterculia lanceolata"
    ]
    


  end
end